### ISSUE TITLE
Getting error for ADD Test Result Keyword

### ISSUE THREAD

**Issue by Bhagya12** [IlfirinPL/robotframework-testmanagement#1]
Dear ,

I am using Add test result keyword with test set id but its gving error as
WARN No result found for FormattedID = "TS43501" 
FAIL ValueError: No result found 

Add Test Result    TC851400  IC13  Fail  Updated through Automation  @{list}  Bhagyashree Bhoyar  test_set=TS43501

Add Test Result    TC851400  IC13  Fail  Updated through Automation  @{list}  Bhagyashree Bhoyar  TS43501

However , if we don use test set id then result gets updated.
But my requirement is to use test set id.

Can you please check?

**Comment by IlfirinPL** [comment]
Can you double check if you are providing proper id and during connection to rally you are using proper workspace, also please try to add log_file in Connect To Rally to see more info about this issue

**Comment by Bhagya12** [comment]
Hi,

I have checked it multiple time for test set id  but still its giving the same errror.
If we don provide the test set id then test case status gets updated but in test folder but i want my test case status to be updated under created test set.

Same error im getting in log file.

This url is generted with test set id  
https://rally1.rallydev.com/slm/webservice/v2.0/TestCase?fetch=true&query=(FormattedID%20%3D%20%22TS43318/%22)&workspace=workspace/462253075&project=project/6912728204&pagesize=100&start=1

Output:{"QueryResult": {"_rallyAPIMajor": "2", "_rallyAPIMinor": "0", "Errors": [], "Warnings": [], "TotalResultCount": 0, "StartIndex": 1, "PageSize": 100, "Results": []}}

But if we try to update using test case id then 

https://rally1.rallydev.com/slm/webservice/v2.0/TestCase?fetch=true&query=(FormattedID%20%3D%20%22TC851400 /%22)&workspace=workspace/462253075&project=project/6912728204&pagesize=100&start=1

After hitting this url , it gives complete records properly

**Comment by IlfirinPL** [comment]
I have notice that generated url is different  is TS43318 in working example is  TC851400, did you tried with different id, because it look like its using TestSuite id instead of TestCase id.

**Comment by Bhagya12** [comment]
Yes first url when i use test set id -- output is error

Second url when i use test case id : working fine

**Comment by IlfirinPL** [comment]
So its working as expected this method is for using test case id, (adding new test results).

**Comment by Bhagya12** [comment]
But there is parameter as test_set ,so i want to use this parameter 

test_case_id, build, verdict, notes=None, attachment_list=None, date=None, tester=None, test_set=None, duration=None

I have used like 
Add Test Result    TC851400  IC13  ${verdict}  Updated through Automation  @{list}  xyz   test_set=TS43501

so its giving error like 
WARN No result found for FormattedID = "TS43501" 
FAIL ValueError: No result found

**Comment by IlfirinPL** [comment]
I have check your test case id, logs below, url is generated properly do you use most recent build ? (robotframework-testmanagement (0.1.2))

20150701 15:36:45.157 :  INFO : 
Add test result:
        FormattedID: TC851400
        Build: IC13
        Verdict: Fail
        Date: None
        Tester: None
        TestSet: None
        Notes: None
        Duration: None
        Attachment_list: None
20150701 15:36:45.157 :  INFO : Constructed query: FormattedID = "TC851400"
20150701 15:36:45.158 :  INFO : url: https://rally1.rallydev.com/slm/webservice/v2.0/TestCase?fetch=true&query=(FormattedID%20%3D%20%22TC851400%22)&workspace=workspace/9226439617&pagesize=100&start=1
20150701 15:36:45.408 :  WARN : No result found for FormattedID = "TC851400"
20150701 15:36:45.412 :  FAIL : ValueError: No result found

**Comment by Bhagya12** [comment]
Yes i m using most recent build .It is working for all other parameters from "Add Test Result" keyword except test_set parameter and that is causing problem :(

Do u have any other solution to update the test results under test sets

**Comment by IlfirinPL** [comment]
Try new build 0.1.10 it should fix this issue, add test results to test set. Using argument test_set=TSXXXX

**Comment by IlfirinPL** [comment]
fixed
